CREATE DATABASE IF NOT EXISTS ACTIVITY_TRACKER;

USE ACTIVITY_TRACKER;

DROP TABLE IF EXISTS USER;
CREATE TABLE USER(
  ID INT NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(200) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  LAST_LOGIN_TIMESTAMP TIMESTAMP NOT NULL,
  USER_ROLE ENUM('ADMIN','USER') NOT NULL DEFAULT 'USER',
  PRIMARY KEY(ID),
  INDEX(USERNAME)
);