INSERT INTO ACTIVITY_TRACKER.USER(USERNAME,PASSWORD,LAST_LOGIN_TIMESTAMP,USER_ROLE)
VALUES
  ('admin','$2y$10$DSgVbu15QpxIBv2Cnub7fexkBMu9MqhtYUaouE6DRrnsZZdetmBqi',NOW(),'ADMIN'),
  ('user1@user.com','$2y$10$3p/ch3cJsfH.Tcf5xkbma.pv.so0Y8WGmZ91y.Lr3EWvztZOz0UG2',NOW(),'USER');